YS_Design/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),  
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('services/', include('services.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name= 'blog'
urlpatterns = [
    path('', views.index, name='blog'),
    path('single_blog/<int:id>/', views.single_blog, name='single_blog'),
    path('submit_comment/', views.submit_comment, name='submit_comment'),

]

portfolio/urls.py
from django.urls import path
from . import views
app_name= 'portfolio'
urlpatterns = [
    path('', views.index, name='portfolio'),
    path('<int:id>', views.single_portfolio, name='single_portfolio'),
]

portfolio/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from ckeditor.fields import RichTextField
# Create your models here.
class postForm(models.Model):
    title = models.CharField(max_length=50)

    # Use FileField with FileExtensionValidator
    image = models.FileField(
        upload_to='media/',
        blank=True,
        null=True,
        default='no-image.png',
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff'])]
    )
    summary = models.CharField(max_length=200,null=True)
    body = RichTextField()
    author = models.CharField(max_length=50, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import postForm
# Create your views here.
def index(request):
    pF = postForm.objects.all()
    return render(request, 'portfolio/index.html', {'pF': pF})
def single_portfolio(request, id):
    pD = postForm.objects.get(id=id)
    return render(request, 'portfolio/single_portfolio.html', {'pD': pD})

portfolio/templates/portfolio/index.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}

    <div id="colorlib-work">
      <div class="container">
        <div class="row text-center">
          <h2 class="bold">Portfolio</h2>
        </div>
        <div class="row">
          <div class="col-md-12 col-md-offset-0 text-center animate-box intro-heading">
            <span>Portfolio</span>
            <h2>Done Projects</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="rotate">
              <h2 class="heading">Portfolio</h2>
            </div>
          </div>
        </div>
        <div class="row">
          {% for item in pF %}
          <div class="col-md-12">
            <div class="work-entry animate-box">
              <a href="{% url 'portfolio:single_portfolio' item.pk %}" class="work-img" style="background-image:url({{item.image.url}});">
                <div class="display-t">
                  <div class="work-name">
                    <h2>{{item.title}}</h2>
                  </div>
                </div>
              </a>
              <div class="col-md-4 col-md-offset-4">
                <div class="desc">
                  <p>{{item.summary}}</p> <p class="read">
                    <a href="#">View details</a>
                  </p>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}

        </div>
      </div>
    </div>


{% endblock %}

portfolio/templates/portfolio/single_portfolio.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}

    <div id="colorlib-work">
      <div class="container">
        <div class="row text-center">
          <h2 class="bold">Portfolio</h2>
        </div>
        <div class="row">
          <div class="col-md-12 col-md-offset-0 text-center animate-box intro-heading">
            <span>Portfolio</span>
            <h2>Portfolio Single</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="rotate">
              <h2 class="heading">Portfolio</h2>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="work-entry animate-box">
              <a href="#" class="work-img" style="background-image:url({{pD.image.url}});"></a>
              <div class="col-md-8 col-md-offset-2">
                <div class="desc">
                  <h2>{{pD.title}}</h2>
                  {{ pD.body | safe }}


                  
                    <a href="#">Live Preview</a>
                 
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

 
{% endblock %}