YS_Design/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),  
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('services/', include('services.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/urls.py
from django.urls import path
from . import views
app_name = 'about'
urlpatterns = [
    path('', views.index,name='about'),
]

blog/urls.py
from django.urls import path
from . import views

app_name= 'blog'
urlpatterns = [
    path('', views.index, name='blog'),
    path('single_blog/<int:id>/', views.single_blog, name='single_blog'),
    path('submit_comment/', views.submit_comment, name='submit_comment'),

]

contact/urls.py
from django.urls import path
from . import views
app_name= 'contact'
urlpatterns = [
    path('', views.index, name='contact'),
    path('getContact/', views.getContact, name='saveContact'),
]

home/urls.py
from django.urls import path
from . import views
app_name= 'home'
urlpatterns = [
    path('', views.index, name='home'),
    
]

portfolio/urls.py
from django.urls import path
from . import views
app_name= 'portfolio'
urlpatterns = [
    path('', views.index, name='portfolio'),
    path('<int:id>', views.single_portfolio, name='single_portfolio'),
]

services/urls.py
from django.urls import path
from . import views
app_name= 'services'
urlpatterns = [
    path('', views.index, name='services'),
]

home/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
class postImg(models.Model):
    # Use FileField with FileExtensionValidator
    image = models.FileField(
        upload_to='media/',
        blank=True,
        null=True,
        default='no-image.png',
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff'])]
    )
class subForm(models.Model):
    email= models.EmailField()
    def __str__(self) :
        return self.email
    

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import postImg 
from services.models import postImg as imgCT
from blog.models import postForm as bl
from portfolio.models import postForm as sp
from contact.models import contactForm 
from contact.forms import contact_Form 
from about.models import postAbout
from .models import subForm
# Create your views here.
def index(request):
    pA=postAbout.objects.all()
    sF = subForm.objects.all()
    form = contact_Form()
    avt=postImg.objects.all()
    iC=imgCT.objects.all()
    pF = bl.objects.order_by('-created_at')[:4]
    pFF = sp.objects.order_by('-created_at')[:4]
    return render(request,'home/index.html',{'avt':avt,'pF':pF,'pFF':pFF,'form':form,'iC':iC,'sF':sF,'pA':pA})


def single_blog(request, id):
    pD = bl.objects.get(id=id)
    return render(request, 'home/index.html', {'pD': pD})
# @receiver(post_save, sender=postForm)

def single_blog(request, id):
    pDD = sp.objects.get(id=id)
    return render(request, 'home/index.html', {'pDD': pDD})
def getContact(request):
    if request.method == "POST":
        form = contact_Form(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'home/index.html')
        else:
            context = {'form': form}
            return render(request, 'contact/index.html', context)
    else:
        return HttpResponse("Error, not a POST request")
    
def saveContact(request):
    if request.method == "POST":
        form = contact_Form(request.POST)
        if form.is_valid():
            saveForm=subForm( email=form.cleaned_data['email'])
            saveContact.save()
           
            return render(request, 'home/index.html')
        else:
            context = {'form': form}
            return render(request, 'contact/index.html', context)
    else:
        return HttpResponse("Error, not a POST request")

home/templates/home/base.html
<!DOCTYPE HTML>
<html>
	<head>
        {% load static %}
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Nhu Y Design</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<meta name="author" content="" />

  <!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="{% static 'favicon.ico' %}">

	<link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700" rel="stylesheet">
	
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'home/css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'home/css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'home/css/bootstrap.css' %}">
	<!-- Owl Carousel -->
	<link rel="stylesheet" href="{% static 'home/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'home/css/owl.theme.default.min.css' %}">
	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static 'home/css/magnific-popup.css' %}">

	<link rel="stylesheet" href="{% static 'home/css/style.css' %}">


	<!-- Modernizr JS -->
	<script src="{% static 'home/js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'home/js/respond.min.js' %}"></script>
	<![endif]-->

	</head>
	<body>
        <nav id="colorlib-main-nav" role="navigation">
            <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle active"><i></i></a>
            <div class="js-fullheight colorlib-table">
                <div class="colorlib-table-cell js-fullheight">
                
                    <div class="row">
                        <div class="col-md-12">
                            <ul>
                                <li class="active"><a href="{% url 'home:home' %}">Home</a></li>
                                <li><a href="{% url 'services:services' %}">Services</a></li>
                                <li><a href="{% url 'portfolio:portfolio' %}">Portfolio</a></li>
                                <li><a href="{% url 'blog:blog' %}">Blog</a></li>
                                <li><a href="{% url 'about:about' %}">About</a></li>
                                <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <h2 class="head-title">Portfolio</h2>
                            <a href="{% static 'home/images/work-8.jpg' %}" class="gallery image-popup-link text-center" style="background-image: url('{% static 'home/images/work-8.jpg' %}');">
                                <span><i class="icon-search3"></i></span>
                            </a>
                            <a href="{% static 'home/images/work-9.jpg' %}" class="gallery image-popup-link text-center" style="background-image: url('{% static 'home/images/work-9.jpg' %}');">
                                <span><i class="icon-search3"></i></span>
                            </a>
                            <a href="{% static 'home/images/work-10.jpg' %}" class="gallery image-popup-link text-center" style="background-image: url('{% static 'home/images/work-10.jpg' %}');">
                                <span><i class="icon-search3"></i></span>
                            </a>
                            <a href="{% static 'home/images/work-11.jpg' %}" class="gallery image-popup-link text-center" style="background-image: url('{% static 'home/images/work-11.jpg' %}');">
                                <span><i class="icon-search3"></i></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
        <div id="colorlib-page">
			<header>
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="colorlib-navbar-brand">
								<a  href="{% url 'home:home' %}"><img src="{% static 'home/images/Screenshot_2023-12-17_210925-removebg-preview.png' %}" alt="" style="width: 70px; height: 70px"></a>
							</div>
							<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
						</div>
					</div>
				</div>
			</header>
		
		
        {% block content %}
        {% endblock content %}
		<footer>
			<div id="footer">
				<div class="container">
					<div class="row">
						<div class="col-md-4 col-pb-sm">
							<div class="row">
								<div class="col-md-10">
									<h2>About Me</h2>
									<a href="#" class="about-img">
										<img class="img-responsive" src="{% static 'home/images/about-3.jpg' %}"
											alt="html5 bootstrap template by colorlib">
									</a>
									<span class="author-name"> Nhu Y  Artistic</span>
									<p>
										"Architecture is not only the organization of space, but also the organization of emotions." 
									</p>
									<p class="colorlib-social-icons">
										<a href="https://www.facebook.com/NhuY.Artistic?mibextid=ZbWKwL"><i class="icon-facebook4"></i></a>
										<a href="https://youtube.com/@nhu.y.artistic?si=gGyDwOOERftzcn6Z"><i class="icon-youtube"></i></a>
										<a href="https://instagram.com/nhu.y.artistic?igshid=NzZlODBkYWE4Ng%3D%3D&utm_source=qr"><i class="icon-instagram2"></i></a>
										<a href="https://www.tiktok.com/@nhu.y.artistic?_t=8i1xFhD6lus&_r=1"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-tiktok" viewBox="0 0 16 16">
											<path d="M9 0h1.98c.144.715.54 1.617 1.235 2.512C12.895 3.389 13.797 4 15 4v2c-1.753 0-3.07-.814-4-1.829V11a5 5 0 1 1-5-5v2a3 3 0 1 0 3 3z"/>
										  </svg></a>
									</p>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-pb-sm">
							<h2>Latest Blog</h2>
							{% for item in pF %}
							<div class="f-entry">
								<a href="#" class="featured-img" style="background-image:url('{% static 'home/images/img-12.jpg' %}');"></a>
								<div class="desc">
								  <span>{{item.created_at}}</span>
								  <h3><a href="#">{{item.title}}</a></h3>
								</div>
							  </div>
							{% endfor %}

						  </div>
						  <div class="col-md-4 col-pb-sm">
							<h2>Newsletter</h2>
							<p>With such great advantages, it is no surprise that interior architecture is considered an extremely important and indispensable art in modern life.</p>
							<form action="{% url 'contact:saveContact' %}" method="post">
								{% csrf_token %}
								<div class="subscribe text-center">
									<div class="form-group">
									  <input type="text" class="form-control text-center" placeholder="Enter Email address" />
									  <input type="submit" value="Subscribe" class="btn btn-primary btn-custom" />
									</div>
								  </div>
							</form>
							
						  </div>
					</div>
	
				</div>
			</div>
		</footer>
	</div>
	<!-- jQuery -->
	<script src="{% static 'home/js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'home/js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'home/js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'home/js/jquery.waypoints.min.js' %}"></script>
	<!-- Owl Carousel -->
	<script src="{% static 'home/js/owl.carousel.min.js' %}"></script>
	<!-- Magnific Popup -->
	<script src="{% static 'home/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'home/js/magnific-popup-options.js' %}"></script>

	<!-- Main JS (Do not remove) -->
	<script src="{% static 'home/js/main.js' %}"></script>

	</body>
</html>