YS_Design/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),  
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('services/', include('services.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name= 'blog'
urlpatterns = [
    path('', views.index, name='blog'),
    path('single_blog/<int:id>/', views.single_blog, name='single_blog'),
    path('submit_comment/', views.submit_comment, name='submit_comment'),

]

blog/models.py
from django.db import models
from django.conf import settings
from django.core.validators import FileExtensionValidator
from ckeditor.fields import RichTextField
# Create your models here.
class postForm(models.Model):
    title = models.CharField(max_length=50)

    # Use FileField with FileExtensionValidator
    image = models.FileField(
        upload_to='media/',
        blank=True,
        null=True,
        default='no-image.png',
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff'])]
    )
    summary = models.CharField(max_length=200,null=True)
    body = RichTextField()
    author = models.CharField(max_length=50, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
class commentForm(models.Model):
    
    name = models.CharField(max_length=50)
    email = models.EmailField()
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) :
        return self.name

blog/views.py
from django.dispatch import receiver
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import postForm
from .models import commentForm
from .form import comment_Form
from django.db.models.signals import post_save
from django.core.paginator import Paginator
# Create your views here.
def index(request):
    pF = postForm.objects.all()
    return render(request, 'blog/index.html', {'pF': pF})
def single_blog(request, id):
    pD = postForm.objects.get(id=id)
    return render(request, 'blog/single_blog.html', {'pD': pD})
def list(request):
    pF = postForm.objects.all()
    paginator = Paginator(pF, 3)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    return render(request, 'blog/index.html', {'posts': posts})
def submit_comment(request):
    if request.method == "POST":
        form = comment_Form(request.POST)
        if form.is_valid():
            # Assuming you have 'post_id' as a field in the comment form to identify the related post
            post_id = form.cleaned_data['post_id']
            post = get_object_or_404(Post, pk=post_id)

            comment, created = Comment.objects.get_or_create(
                name=form.cleaned_data['name'],
                email=form.cleaned_data['email'],
                body=form.cleaned_data['body'],
                post=post,
            )

            post.comments_count = Comment.objects.filter(post=post).count()
            post.save()

            if created:
                return HttpResponse("success")
            else:
                return HttpResponse("Comment already exists")
        else:
            context = {'form': form}
            return render(request, 'blog/index.html', context)
    else:
        return HttpResponse("Error: This is not a POST request")
    
@receiver(post_save, sender=commentForm)
def update_post_comment_count(sender, instance, **kwargs):
    instance.post.comments_count += 1
    instance.post.save()

blog/templates/blog/index.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}

    <div id="colorlib-blog">
        <div class="container">
            <div class="row text-center">
                <h2 class="bold">Blog</h2>
            </div>
            <div class="row">
                <div class="col-md-12 col-md-offset-0 text-center animate-box intro-heading">
                    <span>Blog</span>
                    <h2>Read Our Case</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="rotate">
                        <h2 class="heading">Our Blog</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for item in pF %}
                <div class="col-md-4">
                 
                    <div class="article animate-box">
                        <a href="{% url 'blog:single_blog' item.id %}" class="blog-img">
                            <img src="{{item.image.url}}" alt="html5 bootstrap by colorlib.com">
                            <div class="overlay"></div>
                            <div class="link">
                                <span class="read">Read more</h2>
                            </div>
                        </a>
                        <div class="desc">
                            <span class="meta">{{item.created_at}}</span>
                            <h2><a href="{% url 'blog:single_blog' item.id%}">{{item.title}}</a></h2>

                            <h5><a href="{% url 'blog:single_blog' item.id%}">{{item.author}}  Artistic</a></h2>
                            <p>{{item.summary}}</p>
                        </div>
                    </div>
                 


                </div>
                {% endfor %}


            </div>
        </div>
    </div>



{% endblock %}

blog/templates/blog/single_blog.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}


    <div id="colorlib-blog">
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <div class="blog-entry animate-box col-pb-sm">
                        <a href="#" class="blog-img"><img src="{{pD.image.url}}" class="img-responsive"></a>
                        <div class="desc">
                            <h1><a href="#">{{pD.title}}</a></h1>
                            <span><small>{{pD.created_at}} </small> | <small> blog </small> | <small> <i
                                        class="icon-bubble3"></i> 10</small></span>
                                        {{ pD.body | safe }}
                                               
                            <div class="author text-center">
                                <h3><a href="#">Nhu Y  Artistic</a></h3>
                                <p>Mountains, she had a last view back on the skyline of her hometown
                                    Bookmarksgrove, the headline of Alphabet Village and the subline of her own
                                    road, the Line Lane.</p>
                                <p class="colorlib-social-icons">
                           	<a href="https://www.facebook.com/NhuY.Artistic?mibextid=ZbWKwL"><i class="icon-facebook4"></i></a>
										<a href="https://youtube.com/@nhu.y.artistic?si=gGyDwOOERftzcn6Z"><i class="icon-youtube"></i></a>
										<a href="https://instagram.com/nhu.y.artistic?igshid=NzZlODBkYWE4Ng%3D%3D&utm_source=qr"><i class="icon-instagram2"></i></a>
										<a href="https://www.tiktok.com/@nhu.y.artistic?_t=8i1xFhD6lus&_r=1"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-tiktok" viewBox="0 0 16 16">
											<path d="M9 0h1.98c.144.715.54 1.617 1.235 2.512C12.895 3.389 13.797 4 15 4v2c-1.753 0-3.07-.814-4-1.829V11a5 5 0 1 1-5-5v2a3 3 0 1 0 3 3z"/>
										  </svg></a>
                                </p>
                            </div>
                        </div>
                    </div>

                    {% comment %} <div class="comment-box animate-box">
                        <h2 class="colorlib-heading-2">{{update_post_comment_count}}</h2>
                        {% for comment in submit_comment %}
                        <div class="comment-post">
                            <div class="user" style="background-image:url('{% static 'home/images/person1.jpg' %}');"></div>
                            <div class="desc">
                        {% endfor %}               <h3>{{comment.name}}<span>{{comment.created_at}}</span></h3>
                                <p>{{comment.body|linebreaks}}</p>
                            </div>
                        </div>
                   

                    </div>

                    <div class="comment-area animate-box">
                        <h2 class="colorlib-heading-2">Leave a comment</h2>
                        <form action="{% url 'blog:submit_comment' %}" method="POST">
                            {% csrf_token %}
                            <div class="row form-group">
                                <div class="col-md-6">
                                    <!-- <label for="lname">Last Name</label> -->
                                    <input type="text" id="name" class="form-control" placeholder="Your name">
                                </div>
                            </div>

                            <div class="row form-group">
                                <div class="col-md-12">
                                    <!-- <label for="email">Email</label> -->
                                    <input type="text" id="email" class="form-control"
                                        placeholder="Your email address">
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-md-12">
                                    <!-- <label for="message">Message</label> -->
                                    <textarea name="body" id="body" cols="30" rows="10" class="form-control"
                                        placeholder="Say something about us"></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Post Comment" class="btn btn-primary">
                            </div>

                        </form>
                    </div> {% endcomment %}
                </div>
            </div>
        </div>
    </div>

    <div id="colorlib-instagram">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 col-md-offset-0 text-center">
                    
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="instagram-entry">
                        <a href="#" class="instagram text-center"
                            style="background-image:url('{% static 'home/images/gallery-1.jpg' %}');">
                        </a>
                        <a href="#" class="instagram text-center"
                            style="background-image:url('{% static 'home/images/gallery-2.jpg' %}');">
                        </a>
                        <a href="#" class="instagram text-center"
                            style="background-image:url('{% static 'home/images/gallery-3.jpg' %}');">
                        </a>
                        <a href="#" class="instagram text-center"
                            style="background-image:url('{% static 'home/images/gallery-4.jpg' %}');">
                        </a>
                        <a href="#" class="instagram text-center"
                            style="background-image:url('{% static 'home/images/gallery-5.jpg' %}');">
                        </a>
                        <a href="#" class="instagram text-center"
                            style="background-image:url('{% static 'home/images/gallery-6.jpg' %}');">
                        </a>
                        <a href="#" class="instagram text-center"
                            style="background-image:url('{% static 'home/images/gallery-7.jpg' %}');">
                        </a>
                        <a href="#" class="instagram text-center"
                            style="background-image:url('{% static 'home/images/gallery-8.jpg' %}');">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>




{% endblock %}